#cloud-config

package_update: true
package_upgrade: false

packages:
  - curl
  - docker.io

runcmd:
  - systemctl enable --now docker
  - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v{{ .Version }}+k3s1 K3S_URL=https://{{ .Host }}:{{ .Port }} K3S_TOKEN={{ .Token }} sh -
  - systemctl enable --now k3s-agent

write_files:
  - path: /etc/resolv.conf
    content: |
      nameserver 1.1.1.1
      nameserver 8.8.8.8
      nameserver 8.8.4.4
  - path: /etc/rancher/k3s/registries.yaml
    content: |
      mirrors:
        docker.io:
          endpoint:
            - "https://registry-1.docker.io"
