#cloud-config

package_update: true
package_upgrade: false

packages:
  - nginx

write_files:
  - path: /usr/share/nginx/html/index.html
    content: |
      &lt;!doctype html&gt;
&lt;html lang=&#34;en&#34;&gt;
&lt;head&gt;
  &lt;meta charset=&#34;utf-8&#34;&gt;
  &lt;title&gt;{{ .SiteTitle }}&lt;/title&gt;
  &lt;meta name=&#34;viewport&#34; content=&#34;width=device-width, initial-scale=1&#34;&gt;
  &lt;style&gt;
    body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;padding:2rem;background:#0b132b;color:#e0e6f8}
    .card{max-width:800px;margin:5vh auto;background:#1c2541;border-radius:12px;box-shadow:0 10px 30px rgba(0,0,0,.3);padding:2rem}
    h1{margin:0 0 1rem 0}
    p{opacity:.9;font-size:1.1rem}
  &lt;/style&gt;
&lt;/head&gt;
&lt;body&gt;
  &lt;div class=&#34;card&#34;&gt;
    &lt;h1&gt;{{ .SiteTitle }}&lt;/h1&gt;
    &lt;p&gt;{{ .SiteMessage }}&lt;/p&gt;
  &lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;
  - path: /var/www/html/index.html
    content: |
      &lt;!doctype html&gt;
&lt;html lang=&#34;en&#34;&gt;
&lt;head&gt;
  &lt;meta charset=&#34;utf-8&#34;&gt;
  &lt;title&gt;{{ .SiteTitle }}&lt;/title&gt;
  &lt;meta name=&#34;viewport&#34; content=&#34;width=device-width, initial-scale=1&#34;&gt;
  &lt;style&gt;
    body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;padding:2rem;background:#0b132b;color:#e0e6f8}
    .card{max-width:800px;margin:5vh auto;background:#1c2541;border-radius:12px;box-shadow:0 10px 30px rgba(0,0,0,.3);padding:2rem}
    h1{margin:0 0 1rem 0}
    p{opacity:.9;font-size:1.1rem}
  &lt;/style&gt;
&lt;/head&gt;
&lt;body&gt;
  &lt;div class=&#34;card&#34;&gt;
    &lt;h1&gt;{{ .SiteTitle }}&lt;/h1&gt;
    &lt;p&gt;{{ .SiteMessage }}&lt;/p&gt;
  &lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;

runcmd:
  - if command -v systemctl &gt;/dev/null 2&gt;&amp;1; then
  systemctl enable nginx || true
  systemctl restart nginx || systemctl start nginx || true
else
  service nginx restart || service nginx start || true
fi
